### ISSUE TITLE
duplicate code from cfg GUI and daemon

### ISSUE THREAD

**Issue by albfan** [FreeSpacenav/spnavcfg#13]
Config implementation is mostly duplicated (logging is different but maybe just to stop more copied files)

Is it an option to build daemon and cfg against libspnav and remove duplicated code?

**Comment by jtsiomb** [comment]
The new protocol is mostly in place now, and hacked the spnavcfg GUI to become a libspnav client, which simplified it a lot. Closing this as there is no more code duplication.
