### ISSUE TITLE
Make config GUI aware of changes

### ISSUE THREAD

**Issue by albfan** [FreeSpacenav/spnavcfg#14]
Even if edit manually or if some new actions modify config, GUI should be updated with new config.

we can use inotify: https://www.thegeekstuff.com/2010/04/inotify-c-program-example/

and fork the process to watch the config file, do that makes sense?

**Comment by jtsiomb** [comment]
This will be unnecessary once I finish the new protocol and transition spnavcfg to it.

Btw spacenavd uses inotify for detecting X server socket presence. See `xdetect_linux.c`.
