### ISSUE TITLE
use proper ui file to describe GUI

### ISSUE THREAD

**Issue by albfan** [FreeSpacenav/spnavcfg#15]
Instead of turn ui.xml  into a string, use it as a resource.

I have no idea how to do that on make, but I guess is related with glib-resource-compile.

It is fixed on my branch meson

**Comment by jtsiomb** [comment]
What do you mean "as a resource"?

**Comment by albfan** [comment]
hmm. On gtk2 there's no such concept, so it is just read from file

https://github.com/albfan/spnavcfg/blob/meson/src/main.c#L208

and looks for that file on PKGDATADIR (there're tricks to test that without install, like a dev flag to read file from current location, ...)

in gtk3 you can bundle that file into a glib resource and open it from assigned resources to you app

https://mesonbuild.com/Gnome-module.html#gnomecompile_resources

that needs gtk3. I tested and works

https://docs.gtk.org/gtk3/method.Builder.add_from_resource.html

**Comment by jtsiomb** [comment]
Having to find and read a data file at runtime, to initialize the user interface, is much more complicated and error prone. I see no upside in this. If it could be embedded in the executable that's fine, but isn't that exactly what we are doing now with the conversion of ui.xml to a string?

**Comment by albfan** [comment]
I guess the idea is to use a xml definition to be able to edit visually (glade, cambalache)

Even ui can be created from code.

I just notice touching xml do not trigger any make rework.

This little quirks increase the barrier to contribute or add new features, but as spacenav is almost complete probably not a problem.

Good to have this FTR

**Comment by jtsiomb** [comment]
> I just notice touching xml do not trigger any make rework.
> 
> This little quirks increase the barrier to contribute or add new features, but as spacenav is almost complete probably not a problem.

Changing the XML file triggers a rebuild. That's due to `src/ui.h` being a dependency of the `src/main.o` rule, and it in turn depend ing on `ui/ui.xml` (see Makefile.in).

**Comment by eli-schwartz** [comment]
> in gtk3 you can bundle that file into a glib resource and open it from assigned resources to you app

A glib resource is just a framework for embedding strings into headers/sources, setting up initializers for the gresource runtime, then using GLib pseudo-filepaths and special loader functions to retrieve the string contents out of the gresource framework.

In comparison, manually crafting a header and referencing it as static data works just as well with less overhead.

Regardless of which one you use, the build system (whether Makefile or Meson) would need to add the correct dependency rules to trigger recompilation where needed. With glib-compile-resources there are a few additional things you need to know how to do, unless you have Meson set it up for you -- mainly to do with the fact that you have a second XML file which gets compiled, and it just contains the names of files which internally should be included by the resource compiler.

There's no real point in changing from echo/sed to glib-compile-resources, I guess.
