### ISSUE TITLE
Crash when clicking onto "Serial Device Path"

### ISSUE THREAD

**Issue by hgraeber** [FreeSpacenav/spnavcfg#18]
When the label "Serial Device Path" or the read only input field behind it is clicked the application crashes.
![spnavcfg-1 0](https://user-images.githubusercontent.com/4057854/165292174-ebbb599b-499b-4f96-a57b-4c9b63a327b3.png)

**Comment by jtsiomb** [comment]
Thanks for reporting this. It should be fixed in the latest git commit.
