### ISSUE TITLE
Configuration issues with new installation

### ISSUE THREAD

**Issue by r9labs** [FreeSpacenav/spnavcfg#20]
I'm attempting to compile spnavcfg 1.0 on Ubuntu 20.04 I execute ./configure, which completes successfully. But when I get to the `make` step, I'm met with a series of 
`/usr/bin/ld: src/ui.o: in function `MainWin::spin_changed(int)':
undefined reference to `spnav_cfg_set_deadzone'`

and the compilation fails

there are many more errors related to spnav_cfg options that aren't being set. Is there something obvious that needs to be done to have these variables set?

**Comment by jtsiomb** [comment]
Spnavcfg depends on the latest version of libspnav, which must be installed first.

**Comment by r9labs** [comment]
it has been, although, when I run `make` it still gives me those errors. is it possible the directory structure is not setup correctly? I've noticed these are the only env variables that are set:
`PWD=/home/ryan/Downloads/libspnav-1.0
OLDPWD=/home/ryan/Downloads/spnavcfg-1.0
`

**Comment by jtsiomb** [comment]
Make sure you don't have an older version of libspnav installed elsewhere, and the linker finds the old version first. If all else fails paste the complete build output, and the output of `find / -name 'libspnav*.so*' 2>/dev/null`.

**Comment by jtsiomb** [comment]
Closing since OP did not respond for many months. Feel free to reopen if this is still an issue.
