### ISSUE TITLE
Can't start application: error while loading shared libraries

### ISSUE THREAD

**Issue by Axel-otl** [FreeSpacenav/spnavcfg#22]
OS: voidlinux
init system: runit

Hi, I've been interested in purchasing a  3Dconnexion Spacemouse for use with blender, but I wasn't sure if the proprietary drivers would work. I tried to install this to test if I could use the open source drivers before buying one.

I installed libspnav, spnavcfg, and spacenavd version 1.0
I then made a quick script for spacenavd to use with runit

There were no build errors for any of them, so I tried to run spnavcfg and I get the following message.

spnavcfg: error while loading shared libraries: libspnav.so.0: cannot open shared object file: No such file or directory

**Comment by jtsiomb** [comment]
Did you install libspnav in a prefix where your system's loader expects to find them? In some caes it might also be necessary to run ldconfig after installing new libraries.

**Comment by Axel-otl** [comment]
Running sudo ldconfig fixed it.
Thanks for the quick response!

**Comment by DudeMcGee** [comment]
Still helpful to find this thread here today as of 2025-02-12.
