### ISSUE TITLE
symbol lookup error when running spnavcfg

### ISSUE THREAD

**Issue by ryang3d** [FreeSpacenav/spnavcfg#23]
./configure, make, and make install went smooth, but when I try to launch spnavcfg, I am getting the following error (and the program fails to launch):

`spnavcfg: symbol lookup error: spnavcfg: undefined symbol: spnav_cfg_set_led`

This is on an Ubuntu 20.04 system. Let me know if there is any more info I can provide to troubleshoot, and thanks for sharing this great project!

**Comment by jtsiomb** [comment]
See FAQ #1 in the readme file. You need libspnav 1.0 or later for spnavcfg 1.0 or later. Your linker found libspnav, but it found an older version, lacking the `spnav_cfg_*` entry points.
