### ISSUE TITLE
spacenavcfg crash on button press

### ISSUE THREAD

**Issue by afhp-2020** [FreeSpacenav/spnavcfg#27]
Running `spnavcfg`, built from git on 2022-09-11 on FreeBSD 13.1-RELEASE-p2.
Device is a 3D Connexion Space Explorer.

`spnavcfg` reports an unnamed device on /dev/uhid0 with 0 buttons and 0 axes. The picture displayed does match the physical device.

The "Axes" tab looks normal and responds to device motions.

The "Buttons" tab only shows a container for reporting "Buttons pressed:", initially empty. 

Any button press will crash `spnavcfg` with
```
Assertion failed: (ev.button.bnum < bnrow_count), function spnav_input, file src/ui.cc, line 334.
```
A core dump is generated.

The test programs included with libspnav  all work as expected.
`simple_af_unix` reports:
```
spacenav AF_UNIX protocol version: 1
Device: 
Path: /dev/uhid0
Buttons: 0
Axes: 0
```
The first press on a button reports a series of press events, starting at the actual button pressed, followed by a single press release. 

Here `PANEL` as the first press:
```
 got button press event b(11)
got button press event b(16)
got button press event b(17)
got button press event b(18)
got button press event b(19)
got button press event b(20)
got button press event b(21)
got button press event b(22)
got button press event b(23)
got motion event: t(0, 0, 0) r(0, 0, 0)
got button release event b(11)
got motion event: t(0, 0, 0) r(0, 0, 0)
```
Subsequent presses only report the specific button's press and relase events:
```
got button press event b(11)
got motion event: t(0, 0, 0) r(0, 0, 0)
got button release event b(11)
got motion event: t(0, 0, 0) r(0, 0, 0)
``` 
Pressing `ESC`:
```
got button press event b(6)
got motion event: t(0, 0, 0) r(0, 0, 0)
got button release event b(6)
got motion event: t(0, 0, 0) r(0, 0, 0)
```

`simple_x11` reports the same events, with the only differences being no header with device identification/axes/buttons count.

The complete button mapping is as follows:
```Label Reported
1     b(0)
2     b(1)
T     b(2)
L     b(3)
R     b(4)
F     b(5)
ESC   b(6)
ALT   b(7)
SHIFT b(8)
CTRL  b(9)
FIT   b(10)
PANEL b(11)
+     b(12)
-     b(13)
2D    b(14)
```
All motion events are reported normally.

**Comment by jtsiomb** [comment]
Ok indeed the problem has nothing to do with bug report #27 as I thought.

Unlike other clients which might not have had the time to take the new device identification features of spacenavd into account, spnavcfg uses the number of buttons reported by spacenavd to populate the UI with button mapping rows. Since the FreeBSD USB code does not set number of buttons and axes, the UI expects 0 buttons and chokes when button number N is reported.

So, in order to use the spnavcfg program properly, the spacenavd FreeBSD USB code needs to be fixed to correctly report buttons and axes.

At the same time, it would be nice to change that assertion to something less dramatic, that allows the rest of the configuration UI to function, even if the button mapping interface will be empty.

**Comment by jtsiomb** [comment]
Please test the latest git version of spnavcfg, it should fix the issue. The button mapping interface will be empty until the FreeBSD USB code in spacenavd is improved, but spnavcfg should not crash any more.

**Comment by afhp-2020** [comment]
Pressing a button at random gives an Error dialog: "Received button 5 event on a 0 button device [...] This warning will only be shown once."

No crash. 
Subsequent button presses are silently ignored.
"Buttons" tab remains empty.

The fix works as designed :)

Let me know if I can help with the spacenavd side.

**Comment by jtsiomb** [comment]
Excellent.

On the spacenavd side, you could go through the FreeBSD USB code which is in `src/dev_usb_freebsd.c` and see if you can populate the device `num_axes` and `num_buttons` fields (`dev.h`). You can compare with the Linux code if it's any help: `src/dev_usb_linux.c`. There are more missing features on the FreeBSD side. For instance `src/hotplug_freebsd.c` is a stub at the moment, which means device plugging and unplugging cannot be detected. Feel free to tackle any of that if you feel like it.
