### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by imjonathanking** [FreeSpacenav/spnavcfg#28]
I'm getting this error while trying to run ./spnacfg from the project folder:
"error while loading shared libraries: libspnav.so.0: cannot open shared object file: No such file or directory"

I have uninstalled each program using sudo make uninstall, and reinstalled in this order:
1. spacenavd-1.1
2. libspnav-1.0
3. spnacfg-1.0

I have also added the spacenavd.service considering that my init system is systemd

The fly and simple example applications work from within the libspnav-1.0, but the Cube application throws the error:
"failed to connect to the space navigator daemon"

**Comment by jtsiomb** [comment]
> I'm getting this error while trying to run ./spnacfg from the project folder:
> "error while loading shared libraries: libspnav.so.0: cannot open shared object file: No such file or directory"

That's strange, why would the examples find the library, but not spnavcfg? check all the `libspnav.so*` links to see if the uninstallation failed to remove any stale links, and try running `ldconfig` also. If all else fails please post the output of `ldd ./spnavcfg`.

> The fly and simple example applications work from within the libspnav-1.0, but the Cube application throws the error:
> "failed to connect to the space navigator daemon"

That probably means spacenavd can't connect to the X server, so only programs using the spacenavd-native protocol over UNIX domain sockets will work, but not the 3dconnexion driver compatibility protocol which communicates over X11. The simple example compiles into two flavors, to test both of them. I expect `spnav_af_unix` to work, and `spnav_x11` to fail. Take a look at FAQ 10: https://spacenav.sourceforge.net/faq.html#faq10

**Comment by imjonathanking** [comment]
There was no output of ldconfig. When running "ldd ./spnavcfg", this was the output:
`linux-vdso.so.1 => linux-vdso.so.1 (0x00007ffdd237b000)
	libQt5Widgets.so.5 => /usr/lib/libQt5Widgets.so.5 (0x00007fb119870000)
	libQt5Gui.so.5 => /usr/lib/libQt5Gui.so.5 (0x00007fb119209000)
	libQt5Core.so.5 => /usr/lib/libQt5Core.so.5 (0x00007fb118ce7000)
	libspnav.so.0 => not found
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fb118ba4000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fb11896b000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fb118883000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fb118863000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fb11867c000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x00007fb1185f6000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007fb1185bf000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007fb1185a3000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007fb1184a7000)
	libmd4c.so.0 => /usr/lib/libmd4c.so.0 (0x00007fb118491000)
	libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007fb1183b4000)
	libdouble-conversion.so.3 => /usr/lib/libdouble-conversion.so.3 (0x00007fb11839e000)
	libicui18n.so.71 => /usr/lib/libicui18n.so.71 (0x00007fb11806c000)
	libicuuc.so.71 => /usr/lib/libicuuc.so.71 (0x00007fb117e6b000)
	libpcre2-16.so.0 => /usr/lib/libpcre2-16.so.0 (0x00007fb117dda000)
	libzstd.so.1 => /usr/lib/libzstd.so.1 (0x00007fb117d31000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007fb117bf6000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fb119f71000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fb117bcb000)
	libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007fb117b12000)
	libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007fb117ae0000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007fb117a11000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007fb1179ef000)
	libcap.so.2 => /usr/lib/libcap.so.2 (0x00007fb1179e3000)
	libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007fb11789a000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007fb11786e000)
	liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007fb11784c000)
	libicudata.so.71 => /usr/lib/libicudata.so.71 (0x00007fb115b47000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007fb115acd000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fb115ac8000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fb115abe000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007fb115aab000)
	libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x00007fb115a9d000)
	libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007fb115a77000)
	libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x00007fb115a54000)`

I also wiped everything related to libspnav in:
/usr/local/bin, /usr/local/lib, and /usr/local/include

And then reinstalled everything in the same order with the same outcome. I will continue troubleshooting the X server authentication.

**Comment by jtsiomb** [comment]
Try running `LD_LIBRARY_PATH=/usr/local/lib ./spnavcfg`

**Comment by imjonathanking** [comment]
output of `LD_LIBRARY_PATH=/usr/local/lib ./spnavcfg`:
`Floating point exception (core dumped)`

**Comment by jtsiomb** [comment]
That's a completely unrelated issue. Did you get the spnavcfg source code from git? See FAQ 2: https://github.com/FreeSpacenav/spnavcfg/#faq

**Comment by jtsiomb** [comment]
If LD_LIBRARY_PATH solves the issue with finding the library, it means your system's dynamic loader isn't configured to look into /usr/local/lib for libraries. Ideally you should add that path to the configuration (`/etc/ld.so.conf` or something like that).

**Comment by albfan** [comment]
An easy way to check:

```
$ sudo find /usr -name libspnav.so.0
/usr/lib64/libspnav.so.0
```

if it shows /usr/local/lib just recompile libspnav with

```
./configure --prefix=/usr
```

and install again
