### ISSUE TITLE
connection between cfg and daemon

### ISSUE THREAD

**Issue by albfan** [FreeSpacenav/spnavcfg#31]
I'm trying to rebase work on dominant axis https://github.com/FreeSpacenav/spacenavd/issues/58

but cannot see the connection between cfg and daemon.

Are combo action translated somehow from "Disable rotation" to "disable-rotation"? if so, just add "Dominant axis" will work to add that config?

**Comment by jtsiomb** [comment]
The connection is libspnav.

Disable rotation is mapped to a button action by calling `spnav_cfg_set_bnaction(buttonid, SPNAV_BNACT_DISABLE_ROT)` This in turn results in a `REQ_SCFG_BNACTION` request being sent to the daemon, which is handled by `handle_request()` in `proto_unix.c` of spacenavd. It ends up setting the action id to `cfg.bnact[buttonid]` (see `cfgfile.h`.

So to add a new action, a new enumeration should be added to both libspnav and `cfgfile.h`, and then code in the daemon should take that button action configuration into account, to perform some task when the corresponding button is pressed. For instance in case of disable-rotation, you can see in `handle_button_action` in `event.c` how it sets a global flag, which is then heeded by the `process_input` function.

Hope this helps.

**Comment by albfan** [comment]
Solved, thanks for explanation. https://github.com/FreeSpacenav/spnavcfg/pull/33
