### ISSUE TITLE
fix auto-repeat interval setting

### ISSUE THREAD

**Issue by jtsiomb** [FreeSpacenav/spnavcfg#32]
Setting auto-repeat on the GUI seems to be doing nothing. It was probably left unimplemented initially and was forgotten.

**Comment by albfan** [comment]
I disable global deadzone, set all deadzone to zero and try to see a report on simple example but nothing is reported.

Tested with SpaceNavigator

**Comment by jtsiomb** [comment]
With a zero deadzone, and a device which really returns to 0 on rest, nothing should be reported.

One way to test auto-repeat is to forcefully bottom-down the puck and keep it there without moving it at all. With auto-repeat enabled, you should get a repeated maximum negative-Y event at approximately the repeat interval. With auto-repeat disabled, depending on the device, you might receive just one event and stop until the puck moves again. It's not guaranteed though. If the device itself auto-repeats events, they will still be reported by spacenavd.

**Comment by jtsiomb** [comment]
Fixed. The fix required changes on spnavcfg, libspnav, and spacenavd, because the repeat interval was omitted entirely from the protocol. So the latest git versions of all three are needed for this to work.
