### ISSUE TITLE
Installer as make return error on files

### ISSUE THREAD

**Issue by docop** [FreeSpacenav/spnavcfg#36]
Hi
 I did try to install but fail at some level, like with libspnav, returning an error about a x11.h  -no such file ...  And the gui spnavcfg  too.  Is there any plan to have the release made in a .deb ?  Like it can be only 1 file to install all or 1 .deb to install the whole driver and another for the gui cfg.  
 Look a nice project, but doing a make and fight with version, update and so on..

Thanks in advances

**Comment by jtsiomb** [comment]
No, I'm not interested in distributing pre-compiled binaries. All releases will be source-code only.

If you don't have `X11/Xlib.h` you just need to install the Xlib headers before building spnavcfg.

I'm closing this issue, but feel free to post followup questions if you need further help.

**Comment by jtsiomb** [comment]
Having said that, all parts of the spacenav project are set up to automatically build for GNU/Linux, FreeBSD, and MacOS X, on every commit, for testing. After every automatic build, the results can be downloaded in an archive. So, if you're desparate for a pre-compiled binary, just go to the "Actions" tab at the top of the github page, and pick the latest auto-build for your platform.

**Comment by docop** [comment]
Oh wow ! this is very nice and quite a find, i haven't seen this function usage. So based on action build, that could lead to a just a : dpkg -i spnavcfg  ?    thanks, appreciated

**Comment by jtsiomb** [comment]
No. It doesn't package it up for debian. It just contains the same directory structure that would be produced by running "make install" after building the source. It will have a usr directory, with a bin directory, which contains the spnavcfg executable. Plus some other stuff under usr/share like icons and so on which are not necessary. Just take the executable, and throw it into /usr/local/bin, making sure you set the execute bit, which is not maintained in zip files, and run it.
