### ISSUE TITLE
Yersinia issue

### ISSUE THREAD

**Issue by Midodarwish** [FreeSpacenav/spnavcfg#40]
every time when I try to run yersinia by yersinia -G it gives me that error

mmm... it seems that you don't have gtk support or Yersinia
   has been configured with --disable-gtk option...
   Go and get it!!
how can I fix that

**Comment by jtsiomb** [comment]
What's yersinia, and what does it have to do with spnavcfg?

**Comment by 007gidon** [comment]
> mmm... it seems that you don't have gtk support or Yersinia

same, fixed it?
