### ISSUE TITLE
undefined symbol: spnav_cfg_set_led

### ISSUE THREAD

**Issue by davidrwilliamson** [FreeSpacenav/spnavcfg#44]
I was able to successfully configure and install spnavcfg following the instructions provided. However, on run I get

spnavcfg: symbol lookup error: spnavcfg: undefined symbol: spnav_cfg_set_led

I am using Ubuntu 22.04.1. Before compilation I installed qt5base-dev from apt, and cloned and installed the latest version of libspnav (v1.1) from their Github repo. I have a 3Dconnexion SpaceNavigator plugged in and working (tested in Blender).

**Comment by jtsiomb** [comment]
That's strange... are you certain there isn't a pre-1.0 version of libspnav left installed, and the linker tries to link with that one? Because `spnav_cfg_set_led` should be there from version 1.0 and up. In fact you can check with `nm /usr/local/lib/libspnav.so | grep set_led`.

**Comment by davidrwilliamson** [comment]
That was indeed the problem - a very old version of libspnav from the apt repos had been automatically installed at some point and removing it solved the issue. Thank you for the help!
