### ISSUE TITLE
[0.3] Support user CFLAGS and LDFLAGS

### ISSUE THREAD

**Issue by hartwork** [FreeSpacenav/spnavcfg#5]
Hi!

I added a patch in Gentoo a while back to respect user CFLAGS and LDFLAGS. It seems I forgot to take it upstream so I would like to do that now. Would you be up to git-am [spnavcfg-0.3-custom-flags.patch](https://github.com/gentoo/gentoo/blob/master/x11-misc/spnavcfg/files/spnavcfg-0.3-custom-flags.patch) ? Should I open a pull request?

Thanks and best, Sebastian

**Comment by jtsiomb** [comment]
Indeed, that's a useful change. Do you have something similar for spacenavd? I have "add_cflags" in the spacenavd makefile for this purpose, but it didn't occur to me to set it from the configure script, which is much nicer than having to pass an arbitrary "add_cflags" variable to the make invocation.

**Comment by hartwork** [comment]
> Indeed, that's a useful change.

Cool! How shall we continue about it?

> Do you have something similar for spacenavd? I have "add_cflags" in the spacenavd makefile for this purpose, but it didn't occur to me to set it from the configure script, which is much nicer than having to pass an arbitrary "add_cflags" variable to the make invocation.

There was [this patch for 0.5](https://github.com/gentoo/gentoo/blob/master/app-misc/spacenavd/files/spacenavd-0.5-custom-flags.patch) in the past but [recent 0.7 packaging](https://github.com/gentoo/gentoo/blob/master/app-misc/spacenavd/spacenavd-0.7.ebuild) leverages that very `add_cflags` you mention (and doesn't mind the passing to make due to automation, much).

**Comment by jtsiomb** [comment]
Ok so here's the plan:
1. merge the changes you're proposing for spnavcfg
2. make an equivalent change in the spacenavd configure script to set add_cflags in the makefile if the user specified CFLAGS during configure (and the same for LDFLAGS)

Do you want to make pull requests for either or both of these? Otherwise I can just go and make the changes myself. It's up to you, I don't mind either way.

**Comment by hartwork** [comment]
> Otherwise I can just go and make the changes myself. It's up to you, I don't mind either way.

Given that [/spnavcfg-0.3-custom-flags.patch](https://github.com/gentoo/gentoo/blob/5c1e51e79b20f578740e5a9e98017ae957b0d913/x11-misc/spnavcfg/files/spnavcfg-0.3-custom-flags.patch#L20-L23) drops use of `$(warn) $(dbg) $(opt)` without taking full care of them and that the current spacenavd approach is good enough for my case, I'm happy to accept your offer of taking over.

**Comment by jtsiomb** [comment]
Fixed, commit c9aa215.

**Comment by hartwork** [comment]
Thanks!
