### ISSUE TITLE
[Feature request] Monitor input when moving the device

### ISSUE THREAD

**Issue by Arxcis** [FreeSpacenav/spnavcfg#6]
**Why?**
1. Use as a testing tool to see if the device actually works.
2. It could serve as a demo for developers.

**Prior art**
Here are some inspiration i found. PS4 monitor app https://www.youtube.com/watch?v=SKSqYOwQKhI
More inspo https://www.youtube.com/watch?v=vG9muZ0kWI4

**Comment by jtsiomb** [comment]
There are two such programs included with `libspnav`, they are called `simple` and `cube`. The first one spits out motion and button events to the console, the second allows you to manipulate a 3D cube, and reset its position with any button.

**Comment by Arxcis** [comment]
@jtsiomb Fantastic. Just what I was looking for:
[![asciicast](https://asciinema.org/a/nOaoLj1qpnr7JCoLImtX53DUt.svg)](https://asciinema.org/a/nOaoLj1qpnr7JCoLImtX53DUt)
