### ISSUE TITLE
Multiple icons should not be dumped in /usr/share/pixmaps

### ISSUE THREAD

**Issue by hobbes1069** [FreeSpacenav/spnavcfg#9]
/usr/share/pixmaps is still supported but the old location to put desktop file icons. Most older projects put a single XPM icon there. If multiple sized icons are available they should go in /usr/share/icons/hicolor/<size>x<size>/apps

I have been maintaining the following patch for Fedora for years, I guess I should have submitted this sooner!

```
Index: spnavcfg-0.3.1/Makefile.in
===================================================================
--- spnavcfg-0.3.1.orig/Makefile.in
+++ spnavcfg-0.3.1/Makefile.in
@@ -33,13 +33,10 @@ clean:
 install:
 	$(INSTALL) -d $(DESTDIR)$(PREFIX)/bin
 	$(INSTALL) -m 4775 $(bin) $(DESTDIR)$(PREFIX)/bin/$(bin)
-	mkdir -p $(DESTDIR)$(PREFIX)/share/pixmaps
-	cp icons/spnavcfg-*.png $(DESTDIR)$(PREFIX)/share/pixmaps/
 	for i in 48 128 256; do \
 		destdir=$(DESTDIR)$(PREFIX)/share/icons/hicolor/$${i}x$${i}/apps; \
 		mkdir -p $$destdir; \
-		rm -f $$destdir/spnavcfg-$${i}x$${i}.png; \
-		ln -s $(DESTDIR)$(PREFIX)/share/pixmaps/spnavcfg-$${i}x$${i}.png $$destdir/spnavcfg-$${i}x$${i}.png; \
+		cp -a icons/spnavcfg-$${i}x$${i}.png $$destdir/spnavcfg.png; \
 	done
 	mkdir -p $(DESTDIR)$(PREFIX)/share/applications
 	cp -a icons/spnavcfg.desktop $(DESTDIR)$(PREFIX)/share/applications/
```

**Comment by jtsiomb** [comment]
I'm sure I probably just looked around my filesystem to see where other programs install icons when I came up with this installation rule. I'm not very familiar with distribution conventions. I can see on my debian system that there are some programs with multiple sized icons under pixmaps/ but I guess it does make more sense to put them under icons/hicolor/size/apps indeed.

And yes, it would be best if you could bring any issues you encounter back to me.

Anyway, fixed in rev. 97673e7

**Comment by hobbes1069** [comment]
It would be nice if they put it in more "plain language" but the spec is here:

https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#install_icons

At the top it talks about "other" locations that are checked for icons including "pixmaps". A scalable icon would be nice but I should have thought about that when I exported it from Unigraphics years ago! I wonder if I still have the model laying around.

**Comment by jtsiomb** [comment]
Like an SVG icon? How would a model help with that? I have a shitty space navigator model I made once in blender if it does help in any way: http://mutantstargoat.com/~nuclear/tmp/spacenav.blend

**Comment by hobbes1069** [comment]
Sorry, I should have been more explicit. I contributed the desktop icon many years ago. I modeled my portable spaceball in Unigraphics and exported a PNG. I should have tried to export an SVG.
